apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: ghcr.io/gmdcjdakdcjd/config-service:latest
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8888
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
          resources:
            requests:
              memory: "2Gi"   # 요청 메모리
              cpu: "500m"     # 요청 CPU
            limits:
              memory: "2Gi"   # 제한 메모리
              cpu: "1000m"    # 제한 CPU
