apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
    version: config
    service: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
      version: config
      service: config-service
  template:
    metadata:
      labels:
        app: config-service
        version: config
        service: config-service
    spec:
      containers:
        - name: config-service
          image: ghcr.io/gmdcjdakdcjd/config-service:latest
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 80
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: JAVA_TOOL_OPTIONS
              value: "-Dcom.sun.net.ssl.checkRevocation=false -Dorg.eclipse.jgit.transport.SshSessionFactory=org.eclipse.jgit.transport.JschConfigSessionFactory" #ssl 인증서 무시
