apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
    version: config
    service: config
spec:
  type: ClusterIP
  selector:
    app: config-service
    version: config
    service: config-service
  ports:
    - protocol: TCP
      port: 80
      name: tcp
      targetPort: 8888
